-- Fix timestamp columns to use TIMESTAMPTZ for proper timezone support
ALTER TABLE users
  ALTER COLUMN created_at TYPE TIMESTAMPTZ,
  ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

ALTER TABLE repositories
  ALTER COLUMN created_at TYPE TIMESTAMPTZ,
  ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

ALTER TABLE agent_executions
  ALTER COLUMN started_at TYPE TIMESTAMPTZ,
  ALTER COLUMN completed_at TYPE TIMESTAMPTZ,
  ALTER COLUMN created_at TYPE TIMESTAMPTZ,
  ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

ALTER TABLE workflows
  ALTER COLUMN created_at TYPE TIMESTAMPTZ,
  ALTER COLUMN updated_at TYPE TIMESTAMPTZ;

ALTER TABLE line_messages
  ALTER COLUMN created_at TYPE TIMESTAMPTZ;

ALTER TABLE websocket_connections
  ALTER COLUMN connected_at TYPE TIMESTAMPTZ,
  ALTER COLUMN last_ping_at TYPE TIMESTAMPTZ;

ALTER TABLE execution_logs
  ALTER COLUMN timestamp TYPE TIMESTAMPTZ;

ALTER TABLE tasks
  ALTER COLUMN created_at TYPE TIMESTAMPTZ,
  ALTER COLUMN updated_at TYPE TIMESTAMPTZ,
  ALTER COLUMN started_at TYPE TIMESTAMPTZ,
  ALTER COLUMN completed_at TYPE TIMESTAMPTZ;
