import { LiveProvider, LivePreview, LiveError } from 'react-live';
import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import * as LucideIcons from 'lucide-react';
import { Card, CardBody, CardHeader, Button, Chip, Progress } from '@heroui/react';

/**
 * Dynamic UI Renderer
 *
 * Safely executes and renders React code generated by Gemini 3
 * in a sandboxed environment using react-live.
 *
 * Features:
 * - Isolated execution context
 * - Pre-loaded scope with common libraries
 * - Error boundary with fallback UI
 * - Agent Bridge for user actions
 */

interface DynamicRendererProps {
  /** Generated React code from Gemini 3 */
  code: string;
  /** Additional data to pass to the component */
  data?: any;
  /** Callback when user triggers an action */
  onAction?: (actionType: string, payload: any) => void;
}

export default function DynamicRenderer({
  code,
  data,
  onAction,
}: DynamicRendererProps) {
  const [hasError, setHasError] = useState(false);

  // Reset error state when code changes
  useEffect(() => {
    setHasError(false);
  }, [code]);

  // Prepare scope with all necessary libraries and components
  const scope = {
    // React hooks
    useState,
    useEffect,

    // Animation
    motion,

    // Icons
    ...LucideIcons,

    // UI Components
    Card,
    CardBody,
    CardHeader,
    Button,
    Chip,
    Progress,

    // Data passed from parent
    data,

    // Agent Bridge - allows generated UI to trigger actions
    AgentBridge: {
      triggerAction: (actionType: string, payload?: any) => {
        console.log('[AgentBridge] Action triggered:', actionType, payload);
        onAction?.(actionType, payload);
      },
    },
  };

  // Error fallback UI
  if (hasError) {
    return (
      <motion.div
        initial={{ opacity: 0, scale: 0.9 }}
        animate={{ opacity: 1, scale: 1 }}
        className="p-8 bg-red-50 border-2 border-red-200 rounded-xl"
      >
        <div className="text-center space-y-4">
          <div className="text-6xl">⚠️</div>
          <h3 className="text-xl font-semibold text-red-900">
            UI Generation Error
          </h3>
          <p className="text-red-700">
            The adaptive UI could not be rendered. Please try again.
          </p>
          <Button
            color="danger"
            variant="flat"
            onPress={() => setHasError(false)}
          >
            Retry
          </Button>
        </div>
      </motion.div>
    );
  }

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.6, delay: 0.2 }}
      className="w-full"
    >
      <LiveProvider code={code} scope={scope} noInline={false}>
        {/* Rendered Component */}
        <LivePreview className="w-full" />

        {/* Error Display */}
        <LiveError
          className="mt-4 p-4 bg-red-100 border border-red-300 rounded-lg text-red-800 text-sm font-mono"
          onError={(error: Error) => {
            console.error('[DynamicRenderer] Execution error:', error);
            setHasError(true);
          }}
        />
      </LiveProvider>
    </motion.div>
  );
}
