github:
  defaultPrivate: true
  owner: customer-cloud
  repo: miyabi-private
project:
  gitignoreTemplate: Node
  licenseTemplate: Apache-2.0
labels: {}
workflows:
  autoLabel: true
  autoReview: true
  autoSync: true
cli:
  language: ja
  theme: default
  verboseErrors: true
live_mode:
  enabled: true
  auto_start: true
  voice_enabled: true
  speaker_id: 3
  update_interval: 5
  modes:
    - git
    - files
    - tests
    - build
    - resources
