github:
  defaultPrivate: true
  owner: customer-cloud
  repo: miyabi-private
project:
  gitignoreTemplate: Node
  licenseTemplate: Apache-2.0
labels: {}
workflows:
  autoLabel: true
  autoReview: true
  autoSync: true
cli:
  language: ja
  theme: default
  verboseErrors: true
