# Google Cloud Build Configuration for Miyabi Web API
# Automatically builds and deploys to Cloud Run on push to main branch

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/miyabi-web-api:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/miyabi-web-api:latest'
      - '-f'
      - 'crates/miyabi-web-api/Dockerfile'
      - '.'
    timeout: 1200s # 20 minutes for Rust build

  # Step 2: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/miyabi-web-api:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/miyabi-web-api:latest'

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'miyabi-web-api'
      - '--image=gcr.io/$PROJECT_ID/miyabi-web-api:$COMMIT_SHA'
      - '--region=asia-northeast1' # Tokyo region
      - '--platform=managed'
      - '--allow-unauthenticated' # Required for Telegram webhook
      - '--port=8080'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--max-instances=10'
      - '--min-instances=0' # Scale to zero when idle
      - '--timeout=300' # 5 minutes timeout
      - '--concurrency=80'
      - '--set-env-vars=RUST_LOG=info,SERVER_ADDRESS=0.0.0.0:8080,GITHUB_CLIENT_ID=placeholder,GITHUB_CLIENT_SECRET=placeholder,FRONTEND_URL=https://miyabi-web-api.run.app'
      - '--set-secrets=DATABASE_URL=miyabi-database-url:latest,TELEGRAM_BOT_TOKEN=telegram-bot-token:latest,OPENAI_API_KEY=openai-api-key:latest,GITHUB_TOKEN=github-token:latest,JWT_SECRET=jwt-secret:latest,AUTHORIZED_CHAT_IDS=authorized-chat-ids:latest'
      - '--labels=app=miyabi,component=web-api,env=production'

  # Step 4: Update Telegram Webhook URL
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Get Cloud Run service URL
        SERVICE_URL=$(gcloud run services describe miyabi-web-api \
          --region=asia-northeast1 \
          --format='value(status.url)')

        # Get Telegram Bot Token from Secret Manager
        BOT_TOKEN=$(gcloud secrets versions access latest --secret=telegram-bot-token)

        # Update Telegram Webhook
        curl -X POST "https://api.telegram.org/bot$${BOT_TOKEN}/setWebhook" \
          -d "url=$${SERVICE_URL}/api/v1/telegram/webhook" \
          -d "drop_pending_updates=false"

        echo "Webhook updated to: $${SERVICE_URL}/api/v1/telegram/webhook"

# Build timeout
timeout: 1800s # 30 minutes total

# Images to push
images:
  - 'gcr.io/$PROJECT_ID/miyabi-web-api:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/miyabi-web-api:latest'

# Options
options:
  machineType: 'E2_HIGHCPU_8' # 8 vCPU for faster Rust compilation
  logging: CLOUD_LOGGING_ONLY
  dynamicSubstitutions: true

# Substitutions
substitutions:
  _REGION: 'asia-northeast1'
  _SERVICE_NAME: 'miyabi-web-api'
