#!/bin/bash
# Water Spider Orchestrator - Parallel Tutorial Generation
# Issue #472: 10個のチュートリアルを並列作成

set -e

# tmuxセッション名
SESSION_NAME="miyabi-tutorials"

# 既存のセッションがあれば削除
tmux kill-session -t $SESSION_NAME 2>/dev/null || true

# 新しいtmuxセッションを作成
tmux new-session -d -s $SESSION_NAME -n "tutorial-02"

# tutorial-02用のウィンドウ（既に作成済み）
tmux send-keys -t $SESSION_NAME:tutorial-02 "cd /Users/shunsuke/Dev/miyabi-private/.worktrees/tutorial-02" C-m
tmux send-keys -t $SESSION_NAME:tutorial-02 "cat > tutorial_script.sh << 'SCRIPT'
#!/bin/bash
mkdir -p docs/tutorials
cat > docs/tutorials/02-creating-your-first-agent.md << 'EOF'
# Tutorial 02: Creating Your First Agent

[Tutorial content would be generated by Claude Code here]
This is a placeholder for parallel execution demo.

## Agent Implementation
\\\`\\\`\\\`rust
use miyabi_agents::BaseAgent;
// Implementation...
\\\`\\\`\\\`

EOF

git add docs/tutorials/02-creating-your-first-agent.md
git commit -m 'docs(tutorial): add Tutorial 02 - Creating Your First Agent'
echo 'Tutorial 02 completed'
SCRIPT
" C-m
tmux send-keys -t $SESSION_NAME:tutorial-02 "chmod +x tutorial_script.sh && ./tutorial_script.sh" C-m

# tutorial-03用のウィンドウ
tmux new-window -t $SESSION_NAME -n "tutorial-03"
tmux send-keys -t $SESSION_NAME:tutorial-03 "cd /Users/shunsuke/Dev/miyabi-private/.worktrees/tutorial-03" C-m
tmux send-keys -t $SESSION_NAME:tutorial-03 "cat > tutorial_script.sh << 'SCRIPT'
#!/bin/bash
mkdir -p docs/tutorials
cat > docs/tutorials/03-worktree-parallel-execution.md << 'EOF'
# Tutorial 03: Worktree Parallel Execution

[Tutorial content would be generated by Claude Code here]
This is a placeholder for parallel execution demo.

## Parallel Execution with Git Worktree
\\\`\\\`\\\`bash
git worktree add .worktrees/task-1
# ...
\\\`\\\`\\\`

EOF

git add docs/tutorials/03-worktree-parallel-execution.md
git commit -m 'docs(tutorial): add Tutorial 03 - Worktree Parallel Execution'
echo 'Tutorial 03 completed'
SCRIPT
" C-m
tmux send-keys -t $SESSION_NAME:tutorial-03 "chmod +x tutorial_script.sh && ./tutorial_script.sh" C-m

# tutorial-04用のウィンドウ
tmux new-window -t $SESSION_NAME -n "tutorial-04"
tmux send-keys -t $SESSION_NAME:tutorial-04 "cd /Users/shunsuke/Dev/miyabi-private/.worktrees/tutorial-04" C-m
tmux send-keys -t $SESSION_NAME:tutorial-04 "cat > tutorial_script.sh << 'SCRIPT'
#!/bin/bash
mkdir -p docs/tutorials
cat > docs/tutorials/04-integration-with-github.md << 'EOF'
# Tutorial 04: Integration with GitHub

[Tutorial content would be generated by Claude Code here]
This is a placeholder for parallel execution demo.

## GitHub API Integration
\\\`\\\`\\\`rust
use octocrab::Octocrab;
// Implementation...
\\\`\\\`\\\`

EOF

git add docs/tutorials/04-integration-with-github.md
git commit -m 'docs(tutorial): add Tutorial 04 - Integration with GitHub'
echo 'Tutorial 04 completed'
SCRIPT
" C-m
tmux send-keys -t $SESSION_NAME:tutorial-04 "chmod +x tutorial_script.sh && ./tutorial_script.sh" C-m

echo "====================================================="
echo "🕷️  Water Spider Orchestrator - Parallel Execution"
echo "====================================================="
echo ""
echo "✅ 3つのtmuxウィンドウで並列実行中:"
echo "  - tutorial-02: Creating Your First Agent"
echo "  - tutorial-03: Worktree Parallel Execution"
echo "  - tutorial-04: Integration with GitHub"
echo ""
echo "📊 実行状況の確認:"
echo "  tmux attach -t $SESSION_NAME"
echo ""
echo "⌨️  ウィンドウ切り替え:"
echo "  Ctrl+b n (次のウィンドウ)"
echo "  Ctrl+b p (前のウィンドウ)"
echo "  Ctrl+b 0-9 (ウィンドウ番号で移動)"
echo ""
echo "🚪 tmuxセッション終了:"
echo "  Ctrl+b d (デタッチ)"
echo "  tmux kill-session -t $SESSION_NAME (削除)"
echo ""
echo "====================================================="
