#!/bin/bash
# Issue #472 Tutorial Creation - Command Reference
# Generated by: CoordinatorAgent (しきるん)
# Date: 2025-10-24

set -euo pipefail

# Colors for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Issue #472: Tutorial Creation Commands${NC}"
echo -e "${BLUE}========================================${NC}\n"

# ====================
# Phase 1: Create GitHub Issue
# ====================
echo -e "${GREEN}[Phase 1] Create GitHub Issue${NC}"
echo "Command:"
echo "  gh issue create \\"
echo "    --title '[P4-003] チュートリアル10個作成' \\"
echo "    --label '📥 state:pending,⚠️ priority:P1-High,📚 type:docs' \\"
echo "    --body-file .ai/plans/issue-472-github-issue-body.md"
echo ""

# ====================
# Phase 2: Set up Directory Structure
# ====================
echo -e "${GREEN}[Phase 2] Set up Directory Structure${NC}"
echo "Commands:"
echo "  mkdir -p tutorials/assets/{images,diagrams}"
echo "  touch tutorials/README.md"
echo ""

# ====================
# Phase 3: Execute Task T1 (Beginner Tutorials)
# ====================
echo -e "${GREEN}[Phase 3] Execute Task T1 - Beginner Tutorials${NC}"
echo "Option A: Via Miyabi CLI (if Issue created)"
echo "  miyabi agent run content-creation --issue 472 --task T1"
echo ""
echo "Option B: Via ContentCreationAgent directly"
echo "  # Manually assign task to ContentCreationAgent"
echo "  # Follow tutorial template in .ai/plans/issue-472-plans.md"
echo ""

# ====================
# Phase 4: Verify Task T1 Completion
# ====================
echo -e "${GREEN}[Phase 4] Verify Task T1 Completion${NC}"
echo "Commands:"
echo "  # Check created files"
echo "  ls -lh tutorials/01-*.md tutorials/02-*.md tutorials/03-*.md"
echo ""
echo "  # Count words"
echo "  wc -w tutorials/01-*.md tutorials/02-*.md tutorials/03-*.md"
echo ""
echo "  # Test code examples (Tutorial 1)"
echo "  # Extract and run bash commands from Tutorial 1"
echo "  cargo build --release"
echo "  ./target/release/miyabi --version"
echo ""

# ====================
# Phase 5: Execute Task T2 (Intermediate Tutorials)
# ====================
echo -e "${GREEN}[Phase 5] Execute Task T2 - Intermediate Tutorials${NC}"
echo "Command:"
echo "  miyabi agent run content-creation --issue 472 --task T2"
echo ""

# ====================
# Phase 6: Execute Task T3 (Advanced Tutorials)
# ====================
echo -e "${GREEN}[Phase 6] Execute Task T3 - Advanced Tutorials${NC}"
echo "Command:"
echo "  miyabi agent run content-creation --issue 472 --task T3"
echo ""

# ====================
# Phase 7: Execute Task T4 (Index & Navigation)
# ====================
echo -e "${GREEN}[Phase 7] Execute Task T4 - Index & Navigation${NC}"
echo "Command:"
echo "  miyabi agent run content-creation --issue 472 --task T4"
echo ""

# ====================
# Phase 8: Execute Task T5 (Review & Testing)
# ====================
echo -e "${GREEN}[Phase 8] Execute Task T5 - Review & Testing${NC}"
echo "Commands:"
echo "  # ReviewAgent evaluation"
echo "  miyabi agent run review --issue 472 --task T5"
echo ""
echo "  # Manual code testing"
echo "  for tutorial in tutorials/*.md; do"
echo "    echo \"Testing \$tutorial...\""
echo "    # Extract and test code examples"
echo "  done"
echo ""

# ====================
# Phase 9: Create Pull Request
# ====================
echo -e "${GREEN}[Phase 9] Create Pull Request${NC}"
echo "Commands:"
echo "  git checkout -b feature/tutorials-10"
echo "  git add tutorials/"
echo "  git commit -m 'docs: add 10 comprehensive tutorials (Issue #472)"
echo ""
echo "  🤖 Generated with Claude Code"
echo "  Co-Authored-By: Claude <noreply@anthropic.com>'"
echo ""
echo "  git push origin feature/tutorials-10"
echo ""
echo "  gh pr create \\"
echo "    --title 'docs: add 10 comprehensive tutorials' \\"
echo "    --body 'Closes #472' \\"
echo "    --label '📚 type:docs,✅ state:done'"
echo ""

# ====================
# Phase 10: Update Issue Labels
# ====================
echo -e "${GREEN}[Phase 10] Update Issue Labels${NC}"
echo "Commands:"
echo "  # After PR merged"
echo "  gh issue edit 472 --remove-label '📥 state:pending' --add-label '✅ state:done'"
echo ""

# ====================
# Monitoring Commands
# ====================
echo -e "${YELLOW}[Monitoring] Progress Tracking${NC}"
echo "Commands:"
echo "  # Check task progress"
echo "  gh issue view 472"
echo ""
echo "  # Check ContentCreationAgent logs"
echo "  tail -f .ai/logs/content-creation-agent-*.md"
echo ""
echo "  # Check ReviewAgent scores"
echo "  cat .ai/quality-reports/issue-472-*.json | jq '.overallScore'"
echo ""

# ====================
# Utility Commands
# ====================
echo -e "${YELLOW}[Utilities] Helper Commands${NC}"
echo "Commands:"
echo "  # Word count for all tutorials"
echo "  wc -w tutorials/*.md | tail -1"
echo ""
echo "  # Line count for all tutorials"
echo "  wc -l tutorials/*.md | tail -1"
echo ""
echo "  # Check Mermaid diagrams"
echo "  grep -r '```mermaid' tutorials/"
echo ""
echo "  # List all code blocks"
echo "  grep -r '```' tutorials/ | grep -v mermaid"
echo ""

# ====================
# Testing Commands
# ====================
echo -e "${YELLOW}[Testing] Tutorial Validation${NC}"
echo "Commands:"
echo "  # Test Tutorial 1 (Getting Started)"
echo "  cargo build --release"
echo "  export GITHUB_TOKEN=ghp_xxx"
echo "  export ANTHROPIC_API_KEY=sk-xxx"
echo "  ./target/release/miyabi --version"
echo "  ./target/release/miyabi github status"
echo ""
echo "  # Test Tutorial 5 (Worktree)"
echo "  ./target/release/miyabi agent run coordinator --issues 270,271 --concurrency 2"
echo "  git worktree list"
echo ""

# ====================
# Cleanup Commands
# ====================
echo -e "${YELLOW}[Cleanup] Remove Work-in-Progress Files${NC}"
echo "Commands:"
echo "  # Clean up draft files"
echo "  rm -rf tutorials/drafts/"
echo ""
echo "  # Clean up test outputs"
echo "  rm -rf .ai/test-logs/"
echo ""

echo -e "\n${BLUE}========================================${NC}"
echo -e "${BLUE}End of Command Reference${NC}"
echo -e "${BLUE}========================================${NC}\n"

echo -e "💡 ${GREEN}Quick Start:${NC}"
echo -e "   1. Create Issue: gh issue create --body-file .ai/plans/issue-472-github-issue-body.md"
echo -e "   2. Set up dirs:  mkdir -p tutorials/assets/{images,diagrams}"
echo -e "   3. Start Task T1: miyabi agent run content-creation --issue 472 --task T1"
echo ""

# ====================
# File Verification
# ====================
echo -e "${BLUE}Generated Planning Files:${NC}"
ls -lh .ai/plans/issue-472-* | awk '{print "  "$9" ("$5")"}'
echo ""

echo -e "${GREEN}✅ All commands ready for execution!${NC}\n"
