#!/usr/bin/env node
/**
 * CodeGenAgent - 完全なLark Appコード生成
 *
 * Input: Project Specification (from CoordinatorAgent)
 * Output: Complete application code + package.json + README
 */

import { generateApplication } from './template-engine.js';
import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * CodeGenAgentメインエントリポイント
 * @param {Object} projectSpec - Project specification from Coordinator
 * @returns {Promise<Object>} Generated application metadata
 */
export async function generateLarkApp(projectSpec) {
  console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('🛠️  CodeGenAgent - Lark App Code Generation');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

  const projectName = projectSpec.task_graph.project_name;
  console.log(`📦 Generating: ${projectName}\n`);

  // Step 1: Create project directory
  const outputDir = await createProjectDirectory(projectName);

  // Step 2: Generate main application code
  console.log('═══ Step 1/4: Generate Application Code ═══');
  const appCode = await generateApplication(projectSpec);
  await fs.writeFile(path.join(outputDir, 'index.js'), appCode);
  console.log('✅ index.js created');

  // Step 3: Generate package.json
  console.log('\n═══ Step 2/4: Generate package.json ═══');
  const packageJson = generatePackageJson(projectSpec);
  await fs.writeFile(
    path.join(outputDir, 'package.json'),
    JSON.stringify(packageJson, null, 2)
  );
  console.log('✅ package.json created');

  // Step 4: Generate .env.example
  console.log('\n═══ Step 3/4: Generate .env.example ═══');
  const envExample = generateEnvExample(projectSpec);
  await fs.writeFile(path.join(outputDir, '.env.example'), envExample);
  console.log('✅ .env.example created');

  // Step 5: Generate README.md
  console.log('\n═══ Step 4/4: Generate README.md ═══');
  const readme = generateReadme(projectSpec);
  await fs.writeFile(path.join(outputDir, 'README.md'), readme);
  console.log('✅ README.md created');

  const result = {
    project_name: projectName,
    output_directory: outputDir,
    generated_files: [
      'index.js',
      'package.json',
      '.env.example',
      'README.md',
    ],
    api_count: projectSpec.api_selection.total_apis_selected,
    task_count: projectSpec.task_graph.total_tasks,
    generated_at: new Date().toISOString(),
  };

  console.log('\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
  console.log('✅ Code Generation Complete!');
  console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

  printSummary(result);

  return result;
}

/**
 * プロジェクトディレクトリ作成
 */
async function createProjectDirectory(projectName) {
  const baseDir = path.join(__dirname, '../../output/generated-apps');
  const projectDir = path.join(baseDir, projectName);

  await fs.mkdir(projectDir, { recursive: true });

  console.log(`📁 Project directory: ${projectDir}\n`);

  return projectDir;
}

/**
 * package.json生成
 */
function generatePackageJson(projectSpec) {
  const projectName = projectSpec.task_graph.project_name;

  return {
    name: projectName,
    version: '1.0.0',
    description: `Auto-generated Lark Bot - ${projectSpec.intent_analysis.intent_type}`,
    main: 'index.js',
    type: 'module',
    scripts: {
      start: 'node index.js',
      dev: 'nodemon index.js',
    },
    keywords: ['lark', 'bot', 'automation', 'miyabi'],
    author: 'Miyabi Lark Dev Automation',
    license: 'MIT',
    dependencies: {
      express: '^4.18.2',
      axios: '^1.6.0',
      dotenv: '^16.3.1',
    },
    devDependencies: {
      nodemon: '^3.0.1',
    },
    engines: {
      node: '>=18.0.0',
    },
  };
}

/**
 * .env.example生成
 */
function generateEnvExample(projectSpec) {
  return `# Lark Application Credentials
APP_ID=your_app_id_here
APP_SECRET=your_app_secret_here

# Server Configuration
PORT=3000
LARK_DOMAIN=https://open.larksuite.com

# Optional: Logging
LOG_LEVEL=info
`;
}

/**
 * README.md生成
 */
function generateReadme(projectSpec) {
  const projectName = projectSpec.task_graph.project_name;
  const apis = projectSpec.api_selection.selected_apis;

  return `# ${projectName}

**Auto-generated Lark Bot Application**

Generated by: Miyabi Lark Dev App Automation System
Generated at: ${new Date().toISOString()}

---

## 概要

${projectSpec.user_request}

## 機能

${projectSpec.intent_analysis.functional_requirements
  .map((req, i) => `${i + 1}. ${req}`)
  .join('\n')}

## 使用しているLark APIs

${apis.map(api => `- \`${api}\``).join('\n')}

## セットアップ

### 1. 依存関係インストール

\`\`\`bash
npm install
\`\`\`

### 2. 環境変数設定

\`\`\`bash
cp .env.example .env
# .env ファイルを編集して、APP_ID と APP_SECRET を設定
\`\`\`

### 3. Lark Open Platformで設定

1. [Lark Open Platform](${projectSpec.api_selection.api_specifications[Object.keys(projectSpec.api_selection.api_specifications)[0]]?.documentation_url?.split('/').slice(0, 3).join('/')}) にアクセス
2. 新しいアプリケーションを作成
3. 以下の権限を有効化:

${Array.from(
  new Set(
    Object.values(projectSpec.api_selection.api_specifications).flatMap(
      spec => spec.required_permissions || []
    )
  )
)
  .map(perm => `   - \`${perm}\``)
  .join('\n')}

4. Event Subscriptionを設定:
   - Request URL: \`https://your-domain.com/webhook/events\`
   - Events to subscribe: \`im.message.receive_v1\`

### 4. アプリケーション起動

\`\`\`bash
npm start
\`\`\`

---

## 使い方

1. Larkグループに Bot を追加
2. Bot を @mention してコマンドを送信
3. Bot が応答します

### コマンド例

- \`@Bot help\` - ヘルプ表示
- \`@Bot status\` - ステータス確認

---

## デプロイ

### ngrokを使用したローカルテスト

\`\`\`bash
ngrok http 3000
\`\`\`

ngrokが提供するURLを Lark Event Subscription の Request URL に設定してください。

### プロダクションデプロイ

- Heroku
- AWS Lambda
- Google Cloud Run
- その他のNode.js対応ホスティング

---

## トラブルシューティング

### Botがメッセージに反応しない

1. Event Subscriptionが正しく設定されているか確認
2. Bot に必要な権限が付与されているか確認
3. Request URLが有効で、200を返しているか確認

### Token取得エラー

1. APP_ID と APP_SECRET が正しいか確認
2. アプリケーションが有効化されているか確認

---

## 開発

\`\`\`bash
npm run dev  # nodemon で自動再起動
\`\`\`

---

## ライセンス

MIT

---

**Generated by Miyabi Lark Dev App Automation System**
`;
}

/**
 * サマリー表示
 */
function printSummary(result) {
  console.log('📊 Generated Application Summary:\n');
  console.log(`  Project Name:     ${result.project_name}`);
  console.log(`  Output Directory: ${result.output_directory}`);
  console.log(`  Generated Files:  ${result.generated_files.length}`);
  console.log(`  API Count:        ${result.api_count}`);
  console.log(`  Task Count:       ${result.task_count}\n`);

  console.log('📁 Files:');
  for (const file of result.generated_files) {
    console.log(`  ✅ ${file}`);
  }

  console.log('\n💡 Next Steps:');
  console.log(`  1. cd ${result.output_directory}`);
  console.log('  2. npm install');
  console.log('  3. Configure .env file');
  console.log('  4. npm start');
  console.log('  5. Deploy via DeploymentAgent\n');
}

// CLI実行
if (import.meta.url === `file://${process.argv[1]}`) {
  const specFile = process.argv[2];

  if (!specFile) {
    console.error('❌ Usage: node index.js <project-spec.json>');
    process.exit(1);
  }

  import('fs/promises').then(async fs => {
    const specContent = await fs.readFile(specFile, 'utf-8');
    const projectSpec = JSON.parse(specContent);

    generateLarkApp(projectSpec).then(() => {
      console.log('✅ Code generation complete!');
      process.exit(0);
    });
  }).catch(error => {
    console.error('❌ Code generation failed:', error);
    process.exit(1);
  });
}
