#!/usr/bin/env python3
"""
Lark Tenant Status Report Generator
Generates a PDF report of the current Lark tenant status
"""

from fpdf import FPDF
from datetime import datetime
import os

class LarkReportPDF(FPDF):
    def __init__(self):
        super().__init__()
        # Add Japanese font (M+ 1)
        font_path = os.path.expanduser("~/.fonts/Mplus1-Regular.ttf")
        self.add_font("Mplus1", "", font_path)
        self.set_auto_page_break(auto=True, margin=15)

    def header(self):
        self.set_font("Mplus1", "", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, "Lark Tenant Status Report", align="R")
        self.ln(5)
        self.set_draw_color(200, 200, 200)
        self.line(10, 18, 200, 18)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font("Mplus1", "", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")

    def title_page(self, tenant_name, report_date):
        self.add_page()
        self.ln(40)
        self.set_font("Mplus1", "", 28)
        self.set_text_color(40, 40, 40)
        self.multi_cell(0, 15, "Lark テナント\nステータスレポート", align="C")
        self.ln(20)
        self.set_font("Mplus1", "", 14)
        self.set_text_color(80, 80, 80)
        self.multi_cell(0, 10, tenant_name, align="C")
        self.ln(30)
        self.set_font("Mplus1", "", 12)
        self.set_text_color(120, 120, 120)
        self.cell(0, 10, f"レポート生成日: {report_date}", align="C")
        self.ln(5)
        self.cell(0, 10, "Generated by Miyabi / Claude Code", align="C")

    def section_header(self, title):
        self.set_font("Mplus1", "", 16)
        self.set_text_color(50, 100, 150)
        self.cell(0, 10, title, new_x="LMARGIN", new_y="NEXT")
        self.set_draw_color(50, 100, 150)
        self.line(10, self.get_y(), 100, self.get_y())
        self.ln(5)

    def section_content(self, text):
        self.set_font("Mplus1", "", 10)
        self.set_text_color(60, 60, 60)
        self.multi_cell(0, 6, text)
        self.ln(3)

    def key_value(self, key, value):
        self.set_font("Mplus1", "", 10)
        self.set_text_color(100, 100, 100)
        self.cell(45, 6, key + ":", new_x="RIGHT", new_y="TOP")
        self.set_text_color(40, 40, 40)
        self.multi_cell(0, 6, str(value), new_x="LMARGIN", new_y="NEXT")

    def bullet_item(self, text):
        self.set_font("Mplus1", "", 10)
        self.set_text_color(60, 60, 60)
        self.cell(5)
        self.cell(0, 6, "- " + text, new_x="LMARGIN", new_y="NEXT")


def generate_report():
    pdf = LarkReportPDF()
    report_date = datetime.now().strftime("%Y-%m-%d %H:%M")

    # Title Page
    tenant_name = "Lark公式パートナー カスタマークラウド\n（Startup Fund Group）"
    pdf.title_page(tenant_name, report_date)

    # --- Page 2: Executive Summary ---
    pdf.add_page()
    pdf.section_header("1. エグゼクティブサマリー")

    summary = """本レポートは、Larkテナント「カスタマークラウド」の現在の状態を
API経由で取得し、まとめたものです。

テナントトークンを使用して以下の情報を取得しました：
- テナント基本情報
- 組織構造（部門）
- ユーザー一覧
- グループチャット一覧
- カレンダー
- Wikiスペース"""
    pdf.section_content(summary)
    pdf.ln(5)

    # Quick Stats
    pdf.set_font("Mplus1", "", 12)
    pdf.set_text_color(50, 100, 150)
    pdf.cell(0, 10, "クイック統計", new_x="LMARGIN", new_y="NEXT")

    stats = [
        ("部門数", "1"),
        ("ユーザー数", "2名（API取得分）"),
        ("グループチャット数", "50+"),
        ("カレンダー数", "1"),
        ("Wikiスペース数", "0"),
        ("ユーザーグループ数", "0"),
    ]

    for key, value in stats:
        pdf.key_value(key, value)

    # --- Page 3: Tenant Info ---
    pdf.add_page()
    pdf.section_header("2. テナント基本情報")

    pdf.key_value("テナント名", "Lark公式パートナー カスタマークラウド（Startup Fund Group）")
    pdf.key_value("テナントID", "16122983ce86577d")
    pdf.key_value("Display ID", "LED1ZVZAARO")
    pdf.key_value("テナントタグ", "0（標準テナント）")
    pdf.key_value("アバター", "設定済み")

    pdf.ln(10)
    pdf.section_header("3. 組織構造")

    pdf.set_font("Mplus1", "", 11)
    pdf.set_text_color(40, 40, 40)
    pdf.cell(0, 8, "【部門一覧】", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    pdf.key_value("部門名", "CUSTOMER CLOUD｜プラットフォーム運営管理者")
    pdf.key_value("部門ID", "od-970cb6823b64489db9da8f1fa74a4e30")
    pdf.key_value("メンバー数", "6名")
    pdf.key_value("プライマリメンバー数", "1名")
    pdf.key_value("ステータス", "アクティブ（削除されていない）")
    pdf.key_value("グループチャットID", "oc_70b3ecf5361eca71558401b7e41318ab")

    # --- Page 4: Users ---
    pdf.add_page()
    pdf.section_header("4. ユーザー一覧")

    users = [
        {
            "name": "ハヤシ シュンスケ",
            "email": "hayashi.s@customercloud.ai",
            "enterprise_email": "shunsuke.hayashi@ambitiousai.co.jp",
            "user_id": "b6f97d78",
            "is_tenant_manager": "はい",
            "status": "アクティブ",
            "join_date": "2025-06-23（予定）",
        },
        {
            "name": "木下寛士",
            "en_name": "Hiroshi Kinoshita",
            "email": "kinoshita.h@customercloud.ai",
            "enterprise_email": "ceo@hiroshikinoshita.com",
            "user_id": "2999f2b5",
            "is_tenant_manager": "はい",
            "status": "アクティブ",
            "join_date": "2023-12-12",
        }
    ]

    for i, user in enumerate(users, 1):
        pdf.set_font("Mplus1", "", 11)
        pdf.set_text_color(50, 100, 150)
        pdf.cell(0, 8, f"ユーザー {i}: {user['name']}", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        for key, val in user.items():
            if key == "name":
                continue
            label_map = {
                "en_name": "英語名",
                "email": "メール",
                "enterprise_email": "企業メール",
                "user_id": "ユーザーID",
                "is_tenant_manager": "テナント管理者",
                "status": "ステータス",
                "join_date": "入社日",
            }
            pdf.key_value(label_map.get(key, key), val)
        pdf.ln(5)

    # --- Page 5: Chat Groups ---
    pdf.add_page()
    pdf.section_header("5. グループチャット一覧")

    pdf.section_content("テナント内には50以上のグループチャットが存在します。以下は主要なグループの一部です：")

    chats = [
        ("AiDev Community Hub", "AI開発者のためのコミュニティハブ"),
        ("MCP Development Team", "Lark MCP usage and development"),
        ("Miyabi Dev Team", "Miyabi自律型開発フレームワーク"),
        ("Miyabi Society - 経営戦略チーム", "Society Pantheon/Integrator実装チーム"),
        ("LunchDev - メイン", "遅咲きDevたちが集うメインチャンネル"),
        ("Project TEN 精鋭部隊", "Project TEN受講生のための学習コミュニティ"),
        ("Lark第一人者育成コミュニティ", "Larkで人生を変える学習コミュニティ"),
        ("CHAINON DX推進プロジェクト", "美容室経営のデジタル変革推進"),
        ("TKC仕訳データ連携チーム", "TKC会計システム連携"),
        ("カスタマークラウド - パートナー連携", "Larkパートナー事業の情報共有"),
        ("識学AIアシスタント", "識学理論AIチャットボット"),
        ("製造管理アラート", "在庫不足や緊急案件のアラート通知"),
        ("製造スケジュール管理", "製造スケジュールと進捗管理"),
        ("SNS運用サポート", "SNS運用に関するサポート"),
        ("安全書類管理システム", "建設現場の安全書類管理"),
    ]

    for name, desc in chats:
        pdf.set_font("Mplus1", "", 10)
        pdf.set_text_color(50, 80, 120)
        pdf.cell(0, 6, name, new_x="LMARGIN", new_y="NEXT")
        pdf.set_text_color(100, 100, 100)
        pdf.cell(5)
        pdf.multi_cell(0, 5, desc)
        pdf.ln(2)

    pdf.ln(5)
    pdf.section_content("※ 上記は取得された50以上のチャットグループの一部です")

    # --- Page 6: Calendar & Wiki ---
    pdf.add_page()
    pdf.section_header("6. カレンダー")

    pdf.key_value("カレンダー名", "MCP Integration Tool")
    pdf.key_value("カレンダーID", "feishu.cn_egMihOuILmFTjGFmeehmnd@group.calendar.feishu.cn")
    pdf.key_value("タイプ", "primary")
    pdf.key_value("権限", "private")
    pdf.key_value("ロール", "owner")

    pdf.ln(10)
    pdf.section_header("7. Wikiスペース")
    pdf.section_content("現在、テナントにはWikiスペースが設定されていません。")

    pdf.ln(10)
    pdf.section_header("8. ユーザーグループ")
    pdf.section_content("現在、テナントにはユーザーグループが設定されていません。")

    # --- Page 7: API Access Summary ---
    pdf.add_page()
    pdf.section_header("9. API アクセスサマリー")

    api_results = [
        ("テナント情報 (tenant/v2/tenant/query)", "成功", "テナント基本情報取得"),
        ("部門一覧 (contact/v3/departments)", "成功", "1部門取得"),
        ("ユーザー一覧 (contact/v3/users)", "成功", "2ユーザー取得"),
        ("チャット一覧 (im/v1/chats)", "成功", "50+チャット取得"),
        ("カレンダー (calendar/v4/calendars)", "成功", "1カレンダー取得"),
        ("Wikiスペース (wiki/v2/spaces)", "成功", "0件（空）"),
        ("ユーザーグループ (contact/v3/group/simplelist)", "成功", "0件（空）"),
        ("承認定義 (approval/v4/approvals)", "権限不足", "user_access_token必要"),
        ("アプリ一覧 (application/v6/applications)", "パラメータエラー", "lang必須"),
    ]

    pdf.set_font("Mplus1", "", 9)

    # Table header
    pdf.set_fill_color(50, 100, 150)
    pdf.set_text_color(255, 255, 255)
    pdf.cell(80, 8, "API エンドポイント", border=1, fill=True)
    pdf.cell(25, 8, "結果", border=1, fill=True)
    pdf.cell(75, 8, "備考", border=1, fill=True, new_x="LMARGIN", new_y="NEXT")

    pdf.set_text_color(40, 40, 40)
    for api, status, note in api_results:
        if status == "成功":
            pdf.set_fill_color(230, 255, 230)
        else:
            pdf.set_fill_color(255, 240, 230)
        pdf.cell(80, 7, api[:35], border=1, fill=True)
        pdf.cell(25, 7, status, border=1, fill=True)
        pdf.cell(75, 7, note, border=1, fill=True, new_x="LMARGIN", new_y="NEXT")

    # --- Page 8: Recommendations ---
    pdf.add_page()
    pdf.section_header("10. 推奨事項")

    recommendations = [
        "Wikiスペースの活用: ナレッジ管理のためにWikiスペースの作成を検討",
        "ユーザーグループの設定: 権限管理効率化のためユーザーグループを活用",
        "承認ワークフロー: 業務効率化のため承認機能の導入を検討",
        "アプリ権限の確認: 一部APIで権限不足が発生、必要に応じて権限追加",
        "チャットグループの整理: 50以上のグループがあり、定期的な棚卸しを推奨",
    ]

    for rec in recommendations:
        pdf.bullet_item(rec)

    pdf.ln(15)
    pdf.section_header("11. 備考")

    notes = """• 本レポートはテナントアクセストークンを使用して取得した情報です
• 一部のAPIはユーザーアクセストークンが必要です
• ユーザー数は取得された範囲であり、実際の総数と異なる場合があります
• チャットグループはボットがアクセス可能なもののみが表示されます"""
    pdf.section_content(notes)

    pdf.ln(10)
    pdf.set_font("Mplus1", "", 10)
    pdf.set_text_color(100, 100, 100)
    pdf.cell(0, 10, "--- End of Report ---", align="C")

    # Save PDF
    output_path = os.path.expanduser("~/storage/shared/Download/Lark_Tenant_Report_" +
                                     datetime.now().strftime("%Y%m%d_%H%M") + ".pdf")
    pdf.output(output_path)
    print(f"PDF saved to: {output_path}")
    return output_path


if __name__ == "__main__":
    generate_report()
