#!/bin/bash
# Primitive Script: Human Escalation
# Purpose: Escalate to appropriate human based on error type
# Usage: ./escalate.sh <role> <message> [issue_number]
# Roles: TechLead, CISO, PO, CTO, DevOps

set -e

ROLE="${1:-}"
MESSAGE="${2:-}"
ISSUE_NUM="${3:-}"
PROJECT_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"

if [ -z "$ROLE" ] || [ -z "$MESSAGE" ]; then
    echo "Usage: $0 <role> <message> [issue_number]"
    echo "Roles: TechLead, CISO, PO, CTO, DevOps"
    exit 1
fi

echo "====================================="
echo "Escalation Required"
echo "====================================="
echo "Role: $ROLE"
echo "Time: $(date '+%Y-%m-%d %H:%M:%S')"
echo ""
echo "Message:"
echo "$MESSAGE"
echo ""

if [ -n "$ISSUE_NUM" ]; then
    echo "Related Issue: #$ISSUE_NUM"
    echo ""
fi

# Notification channels
NOTIFICATION_SENT=false

# 1. macOS Notification
if command -v osascript &> /dev/null; then
    osascript -e "display notification \"$MESSAGE\" with title \"Miyabi Escalation: $ROLE\" sound name \"Basso\""
    NOTIFICATION_SENT=true
fi

# 2. VOICEVOX Alert
if [ -f "$PROJECT_ROOT/tools/voicevox_enqueue.sh" ]; then
    "$PROJECT_ROOT/tools/voicevox_enqueue.sh" "エスカレーションが発生しました。ロール: ${ROLE}。${MESSAGE}"
    NOTIFICATION_SENT=true
fi

# 3. Stream Deck Flash (trigger notification file)
STREAM_DECK_FLAG="/tmp/miyabi-escalation-flag"
echo "$(date '+%Y-%m-%d %H:%M:%S') - $ROLE - $MESSAGE" > "$STREAM_DECK_FLAG"

# 4. Create GitHub Issue comment (if issue number provided)
if [ -n "$ISSUE_NUM" ]; then
    gh issue comment "$ISSUE_NUM" --body "## 🚨 Escalation Required

**Role**: $ROLE
**Time**: $(date '+%Y-%m-%d %H:%M:%S')

**Message**:
$MESSAGE

**Action Required**: Please review and take appropriate action.

---
🤖 Generated by Miyabi Automation System" 2>/dev/null || true
fi

# 5. Log to escalation history
LOG_FILE="$PROJECT_ROOT/logs/escalations.log"
mkdir -p "$(dirname "$LOG_FILE")"
echo "[$(date '+%Y-%m-%d %H:%M:%S')] ROLE=$ROLE ISSUE=${ISSUE_NUM:-N/A} MESSAGE=\"$MESSAGE\"" >> "$LOG_FILE"

if [ "$NOTIFICATION_SENT" = true ]; then
    echo "✅ Escalation notifications sent"
else
    echo "⚠️  No notification channels available"
fi

echo ""
echo "Escalation logged to: $LOG_FILE"

exit 0
