@startgantt
!theme plain
printscale daily zoom 2
skinparam backgroundColor white
skinparam defaultFontName "Hiragino Sans"

title 並列実行のイメージ（全体で2.5時間）

project starts 2025-10-22

[つくるん] on {つくるん} starts 2025-10-22 and lasts 1 days
[つくるん] is colored in LightGreen

[かくちゃん] on {かくちゃん} starts 2025-10-23 and lasts 2 days
[かくちゃん] is colored in LightYellow

@endgantt
