import type { DeploymentTask, TerraformExecution } from '@/types/deployment';

export const mockDeploymentTasks: DeploymentTask[] = [
  {
    id: 'task-1020',
    day: 2,
    issueNumber: 1020,
    title: 'Day 2: Docker Image Build & Push to ECR',
    stage: 'docker-ecr',
    status: 'completed',
    progress: 100,
    startTime: '2025-11-18T06:00:00Z',
    endTime: '2025-11-18T06:25:00Z',
    duration: 1500,
    owner: 'MUGEN',
    resources: [
      {
        type: 'ecr_repository',
        name: 'miyabi-web-api',
        status: 'available',
        id: 'miyabi-web-api',
        arn: 'arn:aws:ecr:us-west-2:112530848482:repository/miyabi-web-api',
        createdAt: '2025-11-18T06:10:00Z',
      },
      {
        type: 'docker_image',
        name: 'miyabi-web-api:latest',
        status: 'available',
        id: '112530848482.dkr.ecr.us-west-2.amazonaws.com/miyabi-web-api:latest',
        createdAt: '2025-11-18T06:23:00Z',
      },
    ],
    logs: [
      {
        timestamp: '2025-11-18T06:00:00Z',
        level: 'info',
        message: 'Starting Docker build process',
        source: 'docker',
      },
      {
        timestamp: '2025-11-18T06:10:00Z',
        level: 'success',
        message: 'ECR repository created: miyabi-web-api',
        source: 'aws',
      },
      {
        timestamp: '2025-11-18T06:23:00Z',
        level: 'success',
        message: 'Image pushed successfully to ECR',
        source: 'docker',
      },
    ],
  },
  {
    id: 'task-1021',
    day: 3,
    issueNumber: 1021,
    title: 'Day 3: Deploy VPC, Security Groups & IAM Roles',
    stage: 'vpc-networking',
    status: 'in_progress',
    progress: 35,
    startTime: '2025-11-18T06:30:00Z',
    owner: 'MUGEN',
    resources: [
      {
        type: 'vpc',
        name: 'miyabi-vpc-dev',
        status: 'available',
        id: 'vpc-0123456789abcdef0',
        arn: 'arn:aws:ec2:us-west-2:112530848482:vpc/vpc-0123456789abcdef0',
        createdAt: '2025-11-18T06:32:00Z',
      },
      {
        type: 'subnet',
        name: 'miyabi-public-subnet-1-dev',
        status: 'available',
        id: 'subnet-0a1b2c3d4e5f6g7h8',
        createdAt: '2025-11-18T06:33:00Z',
      },
      {
        type: 'subnet',
        name: 'miyabi-public-subnet-2-dev',
        status: 'available',
        id: 'subnet-1a2b3c4d5e6f7g8h9',
        createdAt: '2025-11-18T06:33:00Z',
      },
      {
        type: 'internet_gateway',
        name: 'miyabi-igw-dev',
        status: 'available',
        id: 'igw-0a1b2c3d4e5f6g7h8',
        createdAt: '2025-11-18T06:34:00Z',
      },
      {
        type: 'nat_gateway',
        name: 'miyabi-nat-1-dev',
        status: 'creating',
        id: 'nat-0a1b2c3d4e5f6g7h8',
      },
    ],
    logs: [
      {
        timestamp: '2025-11-18T06:30:00Z',
        level: 'info',
        message: 'Terraform init completed',
        source: 'terraform',
      },
      {
        timestamp: '2025-11-18T06:31:00Z',
        level: 'info',
        message: 'Terraform plan: 26 resources to create',
        source: 'terraform',
      },
      {
        timestamp: '2025-11-18T06:32:00Z',
        level: 'success',
        message: 'VPC created: vpc-0123456789abcdef0',
        source: 'aws',
      },
      {
        timestamp: '2025-11-18T06:35:00Z',
        level: 'info',
        message: 'Creating NAT Gateway (this may take 5-10 minutes)...',
        source: 'terraform',
      },
    ],
  },
  {
    id: 'task-1022',
    day: 4,
    issueNumber: 1022,
    title: 'Day 4: Deploy ECS Cluster, ALB & Redis',
    stage: 'ecs-alb-redis',
    status: 'blocked',
    progress: 0,
    owner: 'MUGEN',
    resources: [],
    logs: [
      {
        timestamp: '2025-11-18T07:00:00Z',
        level: 'warn',
        message: 'Waiting for Day 3 VPC deployment to complete',
        source: 'terraform',
      },
    ],
  },
  {
    id: 'task-1023',
    day: 5,
    issueNumber: 1023,
    title: 'Day 5: ECS Service Deployment & Validation',
    stage: 'ecs-deployment',
    status: 'pending',
    progress: 0,
    owner: 'MUGEN',
    resources: [],
    logs: [],
  },
  {
    id: 'task-1024',
    day: 6,
    issueNumber: 1024,
    title: 'Day 6: Frontend Connection & E2E Integration Testing',
    stage: 'frontend-integration',
    status: 'pending',
    progress: 0,
    owner: 'Orchestrator',
    resources: [],
    logs: [],
  },
  {
    id: 'task-1025',
    day: 7,
    issueNumber: 1025,
    title: 'Day 7: SSL Setup, Documentation & Final Validation',
    stage: 'ssl-validation',
    status: 'pending',
    progress: 0,
    owner: 'Orchestrator',
    resources: [],
    logs: [],
  },
];

export const mockTerraformExecution: TerraformExecution = {
  phase: 'apply',
  command: 'terraform apply tfplan-day3',
  status: 'in_progress',
  output: [
    'module.networking.aws_vpc.main: Creating...',
    'module.networking.aws_vpc.main: Creation complete after 2s [id=vpc-0123456789abcdef0]',
    'module.networking.aws_subnet.public[0]: Creating...',
    'module.networking.aws_subnet.public[1]: Creating...',
    'module.networking.aws_subnet.public[0]: Creation complete after 1s [id=subnet-0a1b2c3d4e5f6g7h8]',
    'module.networking.aws_subnet.public[1]: Creation complete after 1s [id=subnet-1a2b3c4d5e6f7g8h9]',
    'module.networking.aws_internet_gateway.main: Creating...',
    'module.networking.aws_internet_gateway.main: Creation complete after 1s [id=igw-0a1b2c3d4e5f6g7h8]',
    'module.networking.aws_eip.nat[0]: Creating...',
    'module.networking.aws_eip.nat[0]: Creation complete after 1s',
    'module.networking.aws_nat_gateway.main[0]: Creating...',
    'module.networking.aws_nat_gateway.main[0]: Still creating... [10s elapsed]',
    'module.networking.aws_nat_gateway.main[0]: Still creating... [20s elapsed]',
  ],
  resourcesCreated: 8,
  resourcesUpdated: 0,
  resourcesDestroyed: 0,
  startTime: '2025-11-18T06:31:30Z',
  duration: 180,
};
