import type { Entity, EntityRelation, DatabaseSchema } from '@/types/database'

// Miyabi Core Entities (12 entities)
export const miyabiEntities: Entity[] = [
  // Core Entities
  {
    id: 'E1',
    name: 'Issue',
    description: 'GitHub Issue - タスク管理の起点',
    rustType: 'crates/miyabi-types/src/issue.rs',
    category: 'core',
    fields: [
      { name: 'id', type: 'u64', nullable: false, primaryKey: true },
      { name: 'number', type: 'u32', nullable: false },
      { name: 'title', type: 'String', nullable: false },
      { name: 'body', type: 'String', nullable: true },
      { name: 'state', type: 'IssueState', nullable: false, description: 'open | closed' },
      { name: 'labels', type: 'Vec<String>', nullable: false },
      { name: 'created_at', type: 'DateTime', nullable: false },
      { name: 'updated_at', type: 'DateTime', nullable: false },
    ],
    recordCount: 1248,
  },
  {
    id: 'E2',
    name: 'Task',
    description: 'Issueから分解された実行単位',
    rustType: 'crates/miyabi-types/src/task.rs',
    category: 'core',
    fields: [
      { name: 'id', type: 'Uuid', nullable: false, primaryKey: true },
      { name: 'issue_id', type: 'u64', nullable: false, foreignKey: 'E1' },
      { name: 'title', type: 'String', nullable: false },
      { name: 'status', type: 'TaskStatus', nullable: false, description: 'pending | in_progress | completed' },
      { name: 'assigned_agent', type: 'String', nullable: true, foreignKey: 'E3' },
      { name: 'priority', type: 'u8', nullable: false },
      { name: 'created_at', type: 'DateTime', nullable: false },
    ],
    recordCount: 3742,
  },
  {
    id: 'E3',
    name: 'Agent',
    description: '自律実行Agent（21種類）',
    rustType: 'crates/miyabi-types/src/agent.rs',
    category: 'processing',
    fields: [
      { name: 'id', type: 'String', nullable: false, primaryKey: true },
      { name: 'name', type: 'String', nullable: false },
      { name: 'agent_type', type: 'AgentType', nullable: false, description: 'Coding | Business' },
      { name: 'status', type: 'AgentStatus', nullable: false },
      { name: 'capabilities', type: 'Vec<String>', nullable: false },
      { name: 'execution_count', type: 'u64', nullable: false },
      { name: 'success_rate', type: 'f64', nullable: false },
    ],
    recordCount: 21,
  },
  {
    id: 'E4',
    name: 'PR',
    description: 'Pull Request',
    rustType: 'crates/miyabi-github/src/pr.rs',
    category: 'output',
    fields: [
      { name: 'id', type: 'u64', nullable: false, primaryKey: true },
      { name: 'number', type: 'u32', nullable: false },
      { name: 'issue_id', type: 'u64', nullable: true, foreignKey: 'E1' },
      { name: 'title', type: 'String', nullable: false },
      { name: 'state', type: 'PrState', nullable: false, description: 'open | merged | closed' },
      { name: 'created_by', type: 'String', nullable: false, foreignKey: 'E3' },
      { name: 'created_at', type: 'DateTime', nullable: false },
      { name: 'merged_at', type: 'DateTime', nullable: true },
    ],
    recordCount: 892,
  },
  {
    id: 'E5',
    name: 'Label',
    description: 'GitHub Label（57個の体系）',
    rustType: 'docs/LABEL_SYSTEM_GUIDE.md',
    category: 'core',
    fields: [
      { name: 'id', type: 'u64', nullable: false, primaryKey: true },
      { name: 'name', type: 'String', nullable: false },
      { name: 'color', type: 'String', nullable: false },
      { name: 'category', type: 'LabelCategory', nullable: false },
      { name: 'description', type: 'String', nullable: true },
    ],
    recordCount: 57,
  },
  {
    id: 'E6',
    name: 'QualityReport',
    description: 'コード品質レポート',
    rustType: 'crates/miyabi-types/src/quality.rs',
    category: 'output',
    fields: [
      { name: 'id', type: 'Uuid', nullable: false, primaryKey: true },
      { name: 'pr_id', type: 'u64', nullable: false, foreignKey: 'E4' },
      { name: 'agent_id', type: 'String', nullable: false, foreignKey: 'E3' },
      { name: 'quality_score', type: 'f64', nullable: false },
      { name: 'issues_found', type: 'u32', nullable: false },
      { name: 'recommendations', type: 'Vec<String>', nullable: false },
      { name: 'created_at', type: 'DateTime', nullable: false },
    ],
    recordCount: 654,
  },
  {
    id: 'E7',
    name: 'Command',
    description: 'Claude Codeスラッシュコマンド',
    rustType: '.claude/commands/*.md',
    category: 'workflow',
    fields: [
      { name: 'id', type: 'String', nullable: false, primaryKey: true },
      { name: 'name', type: 'String', nullable: false },
      { name: 'description', type: 'String', nullable: false },
      { name: 'template', type: 'String', nullable: false },
      { name: 'category', type: 'String', nullable: false },
    ],
    recordCount: 15,
  },
  {
    id: 'E8',
    name: 'Escalation',
    description: 'エラーエスカレーション',
    rustType: 'crates/miyabi-types/src/error.rs',
    category: 'workflow',
    fields: [
      { name: 'id', type: 'Uuid', nullable: false, primaryKey: true },
      { name: 'task_id', type: 'Uuid', nullable: false, foreignKey: 'E2' },
      { name: 'error_type', type: 'MiyabiError', nullable: false },
      { name: 'severity', type: 'EscalationLevel', nullable: false },
      { name: 'message', type: 'String', nullable: false },
      { name: 'created_at', type: 'DateTime', nullable: false },
    ],
    recordCount: 127,
  },
  {
    id: 'E9',
    name: 'Deployment',
    description: 'デプロイメント記録',
    rustType: 'crates/miyabi-agents/src/deployment.rs',
    category: 'output',
    fields: [
      { name: 'id', type: 'Uuid', nullable: false, primaryKey: true },
      { name: 'pr_id', type: 'u64', nullable: false, foreignKey: 'E4' },
      { name: 'environment', type: 'String', nullable: false, description: 'dev | staging | prod' },
      { name: 'status', type: 'DeploymentStatus', nullable: false },
      { name: 'deployed_at', type: 'DateTime', nullable: false },
    ],
    recordCount: 342,
  },
  {
    id: 'E10',
    name: 'LDDLog',
    description: 'LDD（Log-Driven Development）ログ',
    rustType: 'crates/miyabi-types/src/workflow.rs',
    category: 'workflow',
    fields: [
      { name: 'id', type: 'Uuid', nullable: false, primaryKey: true },
      { name: 'task_id', type: 'Uuid', nullable: false, foreignKey: 'E2' },
      { name: 'level', type: 'LogLevel', nullable: false },
      { name: 'message', type: 'String', nullable: false },
      { name: 'metadata', type: 'HashMap<String, Value>', nullable: true },
      { name: 'timestamp', type: 'DateTime', nullable: false },
    ],
    recordCount: 15627,
  },
  {
    id: 'E11',
    name: 'DAG',
    description: 'タスク依存グラフ',
    rustType: 'crates/miyabi-types/src/workflow.rs',
    category: 'workflow',
    fields: [
      { name: 'id', type: 'Uuid', nullable: false, primaryKey: true },
      { name: 'issue_id', type: 'u64', nullable: false, foreignKey: 'E1' },
      { name: 'nodes', type: 'Vec<TaskNode>', nullable: false },
      { name: 'edges', type: 'Vec<TaskEdge>', nullable: false },
      { name: 'created_at', type: 'DateTime', nullable: false },
    ],
    recordCount: 421,
  },
  {
    id: 'E12',
    name: 'Worktree',
    description: 'Git Worktree並列実行環境',
    rustType: 'crates/miyabi-worktree/src/lib.rs',
    category: 'workflow',
    fields: [
      { name: 'id', type: 'Uuid', nullable: false, primaryKey: true },
      { name: 'task_id', type: 'Uuid', nullable: false, foreignKey: 'E2' },
      { name: 'path', type: 'PathBuf', nullable: false },
      { name: 'branch_name', type: 'String', nullable: false },
      { name: 'status', type: 'WorktreeStatus', nullable: false },
      { name: 'created_at', type: 'DateTime', nullable: false },
    ],
    recordCount: 289,
  },
]

// Miyabi Entity Relations (27 relations)
export const miyabiRelations: EntityRelation[] = [
  // Issue Processing Flow (R1-R4)
  {
    id: 'R1',
    from: 'E1',
    to: 'E3',
    relationshipType: '1:N',
    label: 'analyzed-by',
    strength: 'high',
    description: 'Issue は IssueAgent によって分析される',
  },
  {
    id: 'R2',
    from: 'E1',
    to: 'E2',
    relationshipType: '1:N',
    label: 'decomposed-into',
    strength: 'high',
    description: 'Issue は複数の Task に分解される',
  },
  {
    id: 'R3',
    from: 'E1',
    to: 'E5',
    relationshipType: 'N:N',
    label: 'tagged-with',
    strength: 'high',
    description: 'Issue は複数の Label でタグ付けされる',
  },
  {
    id: 'R4',
    from: 'E1',
    to: 'E4',
    relationshipType: '1:N',
    label: 'creates',
    strength: 'high',
    description: 'Issue から PR が作成される',
  },

  // Task Management (R5-R7)
  {
    id: 'R5',
    from: 'E2',
    to: 'E3',
    relationshipType: '1:N',
    label: 'assigned-to',
    strength: 'high',
    description: 'Task は Agent に割り当てられる',
  },
  {
    id: 'R6',
    from: 'E2',
    to: 'E2',
    relationshipType: 'N:N',
    label: 'depends-on',
    strength: 'high',
    description: 'Task は他の Task に依存する（DAG）',
  },
  {
    id: 'R7',
    from: 'E2',
    to: 'E12',
    relationshipType: '1:1',
    label: 'executes-in',
    strength: 'high',
    description: 'Task は Worktree で実行される',
  },

  // Agent Execution (R9-R13)
  {
    id: 'R9',
    from: 'E3',
    to: 'E2',
    relationshipType: '1:N',
    label: 'executes',
    strength: 'high',
    description: 'Agent は Task を実行する',
  },
  {
    id: 'R10',
    from: 'E3',
    to: 'E4',
    relationshipType: '1:N',
    label: 'generates',
    strength: 'high',
    description: 'Agent は PR を生成する',
  },
  {
    id: 'R11',
    from: 'E3',
    to: 'E6',
    relationshipType: '1:N',
    label: 'creates',
    strength: 'high',
    description: 'Agent は QualityReport を作成する',
  },
  {
    id: 'R12',
    from: 'E3',
    to: 'E8',
    relationshipType: '1:N',
    label: 'triggers',
    strength: 'low',
    description: 'Agent はエラー時に Escalation をトリガーする',
  },
  {
    id: 'R13',
    from: 'E3',
    to: 'E9',
    relationshipType: '1:N',
    label: 'performs',
    strength: 'high',
    description: 'Agent は Deployment を実行する',
  },

  // PR Relations
  {
    id: 'R14',
    from: 'E4',
    to: 'E6',
    relationshipType: '1:N',
    label: 'reviewed-by',
    strength: 'high',
    description: 'PR は QualityReport でレビューされる',
  },
  {
    id: 'R15',
    from: 'E4',
    to: 'E9',
    relationshipType: '1:N',
    label: 'deployed-as',
    strength: 'high',
    description: 'PR は Deployment としてデプロイされる',
  },

  // Workflow Relations
  {
    id: 'R16',
    from: 'E2',
    to: 'E10',
    relationshipType: '1:N',
    label: 'logs-to',
    strength: 'high',
    description: 'Task は LDDLog を生成する',
  },
  {
    id: 'R17',
    from: 'E2',
    to: 'E8',
    relationshipType: '1:N',
    label: 'escalates-to',
    strength: 'low',
    description: 'Task は失敗時に Escalation を発生させる',
  },
  {
    id: 'R18',
    from: 'E1',
    to: 'E11',
    relationshipType: '1:1',
    label: 'has-dag',
    strength: 'high',
    description: 'Issue は DAG を持つ',
  },
  {
    id: 'R19',
    from: 'E11',
    to: 'E2',
    relationshipType: '1:N',
    label: 'contains',
    strength: 'high',
    description: 'DAG は複数の Task を含む',
  },

  // Command Relations
  {
    id: 'R20',
    from: 'E7',
    to: 'E3',
    relationshipType: 'N:N',
    label: 'invokes',
    strength: 'low',
    description: 'Command は Agent を呼び出す',
  },
  {
    id: 'R21',
    from: 'E7',
    to: 'E2',
    relationshipType: 'N:N',
    label: 'creates',
    strength: 'low',
    description: 'Command は Task を作成できる',
  },

  // Additional Cross-Relations
  {
    id: 'R22',
    from: 'E12',
    to: 'E3',
    relationshipType: '1:N',
    label: 'managed-by',
    strength: 'high',
    description: 'Worktree は Agent によって管理される',
  },
  {
    id: 'R23',
    from: 'E6',
    to: 'E5',
    relationshipType: 'N:N',
    label: 'suggests',
    strength: 'low',
    description: 'QualityReport は Label を提案する',
  },
  {
    id: 'R24',
    from: 'E9',
    to: 'E5',
    relationshipType: 'N:N',
    label: 'tagged-with',
    strength: 'low',
    description: 'Deployment は Label でタグ付けされる',
  },
  {
    id: 'R25',
    from: 'E8',
    to: 'E3',
    relationshipType: '1:N',
    label: 'escalated-to',
    strength: 'high',
    description: 'Escalation は上位 Agent にエスカレートされる',
  },
  {
    id: 'R26',
    from: 'E10',
    to: 'E3',
    relationshipType: '1:N',
    label: 'monitored-by',
    strength: 'high',
    description: 'LDDLog は Agent によって監視される',
  },
  {
    id: 'R27',
    from: 'E11',
    to: 'E3',
    relationshipType: '1:N',
    label: 'orchestrated-by',
    strength: 'high',
    description: 'DAG は CoordinatorAgent によってオーケストレートされる',
  },
]

export const miyabiDatabaseSchema: DatabaseSchema = {
  entities: miyabiEntities,
  relations: miyabiRelations,
}
