#!/bin/bash
# ============================================================================
# 🚀 Miyabi Full System Bootstrap - DANGER MODE
# ============================================================================
# Auto-generated by Operator at $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DANGER_SKIP_MODE=true - All confirmations bypassed
# ============================================================================

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${CYAN}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${CYAN}║     🚀 MIYABI FULL SYSTEM BOOTSTRAP - DANGER MODE             ║${NC}"
echo -e "${CYAN}╚════════════════════════════════════════════════════════════════╝${NC}"

PROJECT_ROOT="/home/ubuntu/miyabi-private"
cd "$PROJECT_ROOT"

# ============================================================================
# WAVE 1: Environment Check (Parallel)
# ============================================================================
echo -e "\n${YELLOW}═══ WAVE 1: Environment Check ═══${NC}"

check_rust() {
    if command -v cargo &> /dev/null; then
        echo -e "${GREEN}✓ Rust: $(cargo --version)${NC}"
        return 0
    else
        echo -e "${RED}✗ Rust not found${NC}"
        return 1
    fi
}

check_node() {
    if command -v node &> /dev/null; then
        echo -e "${GREEN}✓ Node: $(node --version)${NC}"
        return 0
    else
        echo -e "${RED}✗ Node not found${NC}"
        return 1
    fi
}

check_tmux() {
    if command -v tmux &> /dev/null; then
        echo -e "${GREEN}✓ tmux: $(tmux -V)${NC}"
        return 0
    else
        echo -e "${RED}✗ tmux not found${NC}"
        return 1
    fi
}

check_github() {
    if [ -n "$GITHUB_TOKEN" ]; then
        echo -e "${GREEN}✓ GITHUB_TOKEN: configured${NC}"
        return 0
    elif command -v gh &> /dev/null && gh auth status &> /dev/null; then
        export GITHUB_TOKEN=$(gh auth token)
        echo -e "${GREEN}✓ GITHUB_TOKEN: via gh CLI${NC}"
        return 0
    else
        echo -e "${RED}✗ GITHUB_TOKEN: not set${NC}"
        return 1
    fi
}

check_codex() {
    if command -v codex &> /dev/null; then
        echo -e "${GREEN}✓ Codex: $(codex --version 2>/dev/null || echo 'available')${NC}"
        return 0
    else
        echo -e "${YELLOW}⚠ Codex not found (optional)${NC}"
        return 1
    fi
}

# Run checks
check_rust &
RUST_PID=$!
check_node &
NODE_PID=$!
check_tmux &
TMUX_PID=$!
check_github &
GITHUB_PID=$!
check_codex &
CODEX_PID=$!

wait $RUST_PID $NODE_PID $TMUX_PID $GITHUB_PID $CODEX_PID 2>/dev/null || true

# ============================================================================
# WAVE 2: tmux Session Setup
# ============================================================================
echo -e "\n${YELLOW}═══ WAVE 2: tmux Session Setup ═══${NC}"

SESSION_NAME="miyabi-orchestra"

if tmux has-session -t "$SESSION_NAME" 2>/dev/null; then
    echo -e "${GREEN}✓ Session '$SESSION_NAME' already exists${NC}"
else
    echo -e "${CYAN}Creating tmux session: $SESSION_NAME${NC}"
    tmux new-session -d -s "$SESSION_NAME" -c "$PROJECT_ROOT"
    
    # Create 5-pane Coding Ensemble layout
    tmux split-window -h -t "$SESSION_NAME"
    tmux split-window -v -t "$SESSION_NAME"
    tmux select-pane -t "$SESSION_NAME:0.0"
    tmux split-window -v -t "$SESSION_NAME"
    tmux select-pane -t "$SESSION_NAME:0.2"
    tmux split-window -v -t "$SESSION_NAME"
    tmux select-layout -t "$SESSION_NAME" tiled
    
    # Set pane titles
    tmux select-pane -t "$SESSION_NAME:0.0" -T "🎼 Conductor (しきるん)"
    tmux select-pane -t "$SESSION_NAME:0.1" -T "🎹 CodeGen (カエデ)"
    tmux select-pane -t "$SESSION_NAME:0.2" -T "🎺 Review (サクラ)"
    tmux select-pane -t "$SESSION_NAME:0.3" -T "🥁 PR (ツバキ)"
    tmux select-pane -t "$SESSION_NAME:0.4" -T "🎷 Deploy (ボタン)"
    
    echo -e "${GREEN}✓ Coding Ensemble (5-pane) created${NC}"
fi

# ============================================================================
# WAVE 3: Build Rust Binaries (if Rust available)
# ============================================================================
echo -e "\n${YELLOW}═══ WAVE 3: Rust Build ═══${NC}"

if command -v cargo &> /dev/null; then
    echo -e "${CYAN}Building Rust project (release mode)...${NC}"
    cargo build --release 2>&1 | tail -20 || echo -e "${YELLOW}⚠ Build warnings/errors (continuing)${NC}"
    
    if [ -f "target/release/miyabi-mcp-server" ]; then
        echo -e "${GREEN}✓ A2A Bridge built successfully${NC}"
    else
        echo -e "${YELLOW}⚠ A2A Bridge not found after build${NC}"
    fi
else
    echo -e "${YELLOW}⚠ Skipping Rust build (cargo not found)${NC}"
fi

# ============================================================================
# WAVE 4: MCP Server Setup
# ============================================================================
echo -e "\n${YELLOW}═══ WAVE 4: MCP Server Check ═══${NC}"

MCP_SERVERS=(
    "miyabi-tmux-server"
    "miyabi-rules-server"
    "miyabi-github"
    "miyabi-codex"
)

for server in "${MCP_SERVERS[@]}"; do
    server_path="$PROJECT_ROOT/mcp-servers/$server"
    if [ -d "$server_path" ]; then
        if [ -f "$server_path/package.json" ]; then
            echo -e "${GREEN}✓ $server: ready${NC}"
        else
            echo -e "${YELLOW}⚠ $server: no package.json${NC}"
        fi
    else
        echo -e "${RED}✗ $server: not found${NC}"
    fi
done

# ============================================================================
# WAVE 5: Final Status Report
# ============================================================================
echo -e "\n${YELLOW}═══ WAVE 5: Final Status ═══${NC}"

echo -e "${CYAN}System Resources:${NC}"
echo "  CPU: $(grep -c processor /proc/cpuinfo) cores"
echo "  Memory: $(free -h | awk '/^Mem:/ {print $3 "/" $2}')"
echo "  Disk: $(df -h / | awk 'NR==2 {print $3 "/" $2}')"

echo -e "\n${CYAN}tmux Sessions:${NC}"
tmux list-sessions 2>/dev/null || echo "  No sessions"

echo -e "\n${GREEN}╔════════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║     ✅ BOOTSTRAP COMPLETE                                      ║${NC}"
echo -e "${GREEN}╚════════════════════════════════════════════════════════════════╝${NC}"

echo -e "\n${CYAN}Next Steps:${NC}"
echo "  1. tmux attach -t $SESSION_NAME"
echo "  2. Start agents in each pane"
echo "  3. Begin development workflow"
