#!/usr/bin/env bash
#
# AI News Blog Article Generator
# Version: 1.0.0
# Purpose: Automated AI news blog article generator using Claude Code X
#
# Usage:
#   ./scripts/generate-ai-blog.sh [--date YYYY-MM-DD] [--topics "topic1,topic2"]
#

set -euo pipefail

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
OUTPUT_DIR="${PROJECT_ROOT}/docs/blog"
DATE="${DATE:-$(date +%Y-%m-%d)}"
TOPICS="${TOPICS:-AI,LLM,Claude,GPT,Gemini}"

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Parse arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --date)
            DATE="$2"
            shift 2
            ;;
        --topics)
            TOPICS="$2"
            shift 2
            ;;
        --output-dir)
            OUTPUT_DIR="$2"
            shift 2
            ;;
        --help)
            cat <<EOF
AI News Blog Article Generator

Usage:
  $0 [options]

Options:
  --date YYYY-MM-DD     Date for the blog article (default: today)
  --topics "t1,t2"      Comma-separated topics (default: AI,LLM,Claude,GPT,Gemini)
  --output-dir PATH     Output directory (default: docs/blog)
  --help                Show this help message

Examples:
  $0
  $0 --date 2025-10-31 --topics "Claude 4,OpenAI o3"
  $0 --output-dir /tmp/blog

This script generates AI news blog articles using Claude Code with WebSearch capability.
It will research the latest AI news and generate a comprehensive blog article.
EOF
            exit 0
            ;;
        *)
            echo -e "${RED}❌ Unknown option: $1${NC}"
            echo "Use --help for usage information"
            exit 1
            ;;
    esac
done

# Ensure output directory exists
mkdir -p "$OUTPUT_DIR"

OUTPUT_FILE="$OUTPUT_DIR/ai-news-${DATE}.md"

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}AI News Blog Article Generator${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""
echo -e "${YELLOW}Configuration:${NC}"
echo -e "  Date: ${DATE}"
echo -e "  Topics: ${TOPICS}"
echo -e "  Output: ${OUTPUT_FILE}"
echo ""

# Generate the prompt for Claude Code
PROMPT="Generate a comprehensive AI news blog article for ${DATE}.

Research the latest AI news using WebSearch and create a blog article with the following:

## Requirements:
1. Search for the latest news about: ${TOPICS}
2. Focus on developments from the past 7 days
3. Include concrete facts, dates, and company names
4. Cite sources for all information

## Article Structure:
\`\`\`markdown
---
title: \"AI News Digest - ${DATE}\"
date: ${DATE}
tags: [AI, Machine Learning, LLM, News]
author: Miyabi AI News Bot
---

# AI News Digest - ${DATE}

## Executive Summary
[Brief overview of the week's top AI developments]

## Top Stories

### 1. [Headline 1]
- **Source**: [Company/Publication]
- **Date**: [Date]
- **Details**: [Detailed explanation]
- **Impact**: [Why this matters]

### 2. [Headline 2]
[Same structure as above]

### 3. [Headline 3]
[Same structure as above]

## Notable Updates

### Model Releases & Updates
- [List of new model releases with details]

### Research Papers
- [Significant papers published this week]

### Industry News
- [Company announcements, funding, partnerships]

## Developer Tools & Libraries
- [New tools, frameworks, or updates]

## Community Highlights
- [Notable discussions, projects, or trends]

## Looking Ahead
[Upcoming events, releases, or trends to watch]

## Sources
1. [List all sources used]

---

*Generated by Miyabi AI News Bot using Claude Code*
*Last Updated: ${DATE}*
\`\`\`

## Output Instructions:
1. Write the complete article to: ${OUTPUT_FILE}
2. Ensure all facts are verifiable with sources
3. Use clear, engaging writing style
4. Include at least 5-10 news items
5. Format with proper Markdown

Execute this task using WebSearch to find the latest information."

# Check if we're in a Claude Code session
if [ -n "${CLAUDE_SESSION:-}" ]; then
    echo -e "${GREEN}✅ Running in Claude Code session${NC}"
    echo ""
    echo -e "${BLUE}📝 Generating article with prompt:${NC}"
    echo "================================="
    echo "$PROMPT"
    echo "================================="
    echo ""
    echo -e "${YELLOW}💡 Claude Code will now execute this task with WebSearch capability${NC}"
else
    echo -e "${YELLOW}⚠️  Not running in Claude Code session${NC}"
    echo ""
    echo -e "${YELLOW}💡 To use this script properly, run it via Claude Code:${NC}"
    echo ""
    echo -e "  ${BLUE}claude -p \"\$(cat scripts/generate-ai-blog.sh) && execute\"${NC}"
    echo ""
    echo -e "  ${BLUE}Or use Claude Code X:${NC}"
    echo -e "  ${BLUE}/claude-code-x exec \"Generate AI blog article for ${DATE}\"${NC}"
    echo ""
    echo ""
    echo -e "${BLUE}📝 Task Prompt (for manual use):${NC}"
    echo "================================="
    echo "$PROMPT"
    echo "================================="
    echo ""
    echo -e "${YELLOW}Copy the above prompt and paste it to Claude Code${NC}"
fi

# Create a template file if we're not in Claude Code session
if [ -z "${CLAUDE_SESSION:-}" ]; then
    echo -e "${BLUE}📄 Creating template file: ${OUTPUT_FILE}${NC}"

    cat > "$OUTPUT_FILE" <<EOF
---
title: "AI News Digest - ${DATE}"
date: ${DATE}
tags: [AI, Machine Learning, LLM, News]
author: Miyabi AI News Bot
status: draft
---

# AI News Digest - ${DATE}

## Executive Summary

[This article is a draft template. Use Claude Code with WebSearch to generate the full content.]

## How to Generate

Run one of the following commands:

### Option 1: Direct Claude Code
\`\`\`bash
claude -p "Generate AI news blog article for ${DATE}. Research latest news about ${TOPICS} using WebSearch and write to ${OUTPUT_FILE}"
\`\`\`

### Option 2: Claude Code X (Background)
\`\`\`bash
/claude-code-x exec "Generate AI news blog article for ${DATE}"
\`\`\`

## Topics to Cover

- ${TOPICS//,/
- }

---

*Template generated by generate-ai-blog.sh*
*Run with Claude Code to generate full content*
EOF

    echo -e "${GREEN}✅ Template created successfully${NC}"
    echo ""
    echo -e "${YELLOW}💡 Next steps:${NC}"
    echo -e "  1. Run with Claude Code to generate full content"
    echo -e "  2. Or use /claude-code-x exec to run in background"
    echo -e "  3. Review and edit the generated content"
fi

echo ""
echo -e "${GREEN}🎉 Script completed${NC}"
