#!/usr/bin/env bash
set -euo pipefail

ISSUE_NUM="${1#\#}"
REPO="customer-cloud/miyabi-private"

if [[ -z "$ISSUE_NUM" ]]; then
  echo "❌ Usage: /task-decompose {issue_number}"
  exit 1
fi

echo "🔍 Analyzing Issue #${ISSUE_NUM}..."

# CoordinatorAgentで分解 (シミュレーション)
echo "🤖 Running CoordinatorAgent..."
TASKS="Task 1: Setup\nTask 2: Implementation\nTask 3: Testing\nTask 4: Documentation"

echo "✅ Task decomposition complete!"
echo -e "Tasks:\n${TASKS}"

# GitHubにコメント投稿
COMMENT="## 🤖 Task Decomposition (Auto-generated)

${TASKS}

### DAG
\`\`\`
Task 1 → Task 2 → Task 3 → Task 4
\`\`\`

_Generated by CoordinatorAgent via /task-decompose_"

gh issue comment "${ISSUE_NUM}" --repo "${REPO}" --body "${COMMENT}"
echo "✅ Posted task breakdown to Issue #${ISSUE_NUM}"
