#!/usr/bin/env python3
"""
video-generator.py

音声ファイル（WAV）から動画ファイル（MP4）を生成

使用例:
    python video-generator.py --audio-dir ./output/audio --output ./output/video.mp4
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import List


class VideoGenerator:
    """VOICEVOX音声から動画を生成"""

    def __init__(self, audio_dir: Path, output_file: Path, thumbnail: Path = None):
        self.audio_dir = audio_dir
        self.output_file = output_file
        self.thumbnail = thumbnail or self._create_default_thumbnail()
        self.temp_dir = audio_dir.parent / "temp"
        self.temp_dir.mkdir(exist_ok=True)

    def _create_default_thumbnail(self) -> Path:
        """デフォルトサムネイル画像を生成（1920x1080の単色背景）

        BytePlus ARK APIで生成されたカスタムサムネイルが存在する場合はそれを使用
        """
        output_dir = self.audio_dir.parent
        thumbnail_path = output_dir / "thumbnail.png"

        if thumbnail_path.exists():
            # BytePlus ARK APIで生成されたカスタムサムネイルを使用
            print(f"🎨 カスタムサムネイルを使用: {thumbnail_path}")
            return thumbnail_path

        # カスタムサムネイルが存在しない場合、デフォルトを生成
        print(f"⚠️  カスタムサムネイルが見つかりません。デフォルトを生成します...")

        # ffmpegで単色背景画像を生成
        cmd = [
            "ffmpeg",
            "-f", "lavfi",
            "-i", "color=c=0x1a1a2e:s=1920x1080:d=1",
            "-frames:v", "1",
            "-y",
            str(thumbnail_path)
        ]
        subprocess.run(cmd, capture_output=True, check=True)
        print(f"✅ デフォルトサムネイルを生成: {thumbnail_path}")

        return thumbnail_path

    def collect_audio_files(self) -> List[Path]:
        """音声ファイルを収集してソート"""
        audio_files = sorted(self.audio_dir.glob("speaker*.wav"))
        if not audio_files:
            raise FileNotFoundError(f"音声ファイルが見つかりません: {self.audio_dir}")

        print(f"🎤 {len(audio_files)}件の音声ファイルを検出")
        return audio_files

    def concatenate_audio(self, audio_files: List[Path]) -> Path:
        """複数の音声ファイルを1つに連結"""
        concat_list = self.temp_dir / "concat_list.txt"
        merged_audio = self.temp_dir / "merged_audio.wav"

        # ffmpeg concat用のリスト作成
        with open(concat_list, "w") as f:
            for audio_file in audio_files:
                f.write(f"file '{audio_file.absolute()}'\n")

        # 音声ファイルを連結
        cmd = [
            "ffmpeg",
            "-f", "concat",
            "-safe", "0",
            "-i", str(concat_list),
            "-c", "copy",
            "-y",
            str(merged_audio)
        ]

        subprocess.run(cmd, capture_output=True, check=True)
        print(f"✅ 音声ファイルを連結: {merged_audio}")

        return merged_audio

    def generate_video(self, merged_audio: Path) -> None:
        """音声と画像から動画を生成"""
        print(f"🎬 動画生成開始: {self.output_file}")

        cmd = [
            "ffmpeg",
            "-loop", "1",                          # 画像をループ
            "-i", str(self.thumbnail),             # 入力画像
            "-i", str(merged_audio),               # 入力音声
            "-c:v", "libx264",                     # H.264エンコーダ
            "-tune", "stillimage",                 # 静止画最適化
            "-c:a", "aac",                         # AACオーディオ
            "-b:a", "192k",                        # オーディオビットレート
            "-pix_fmt", "yuv420p",                 # ピクセルフォーマット
            "-shortest",                           # 音声の長さに合わせる
            "-movflags", "+faststart",             # Web再生最適化
            "-metadata", "title=Miyabi開発進捗 - ゆっくり解説",
            "-metadata", "artist=NarrationAgent",
            "-metadata", "comment=Generated by Miyabi NarrationAgent",
            "-y",
            str(self.output_file)
        ]

        result = subprocess.run(cmd, capture_output=True, text=True)

        if result.returncode != 0:
            print(f"❌ 動画生成エラー: {result.stderr}", file=sys.stderr)
            raise RuntimeError("ffmpeg execution failed")

        print(f"✅ 動画生成完了: {self.output_file}")

    def get_video_info(self) -> dict:
        """生成された動画の情報を取得"""
        cmd = [
            "ffprobe",
            "-v", "quiet",
            "-print_format", "json",
            "-show_format",
            "-show_streams",
            str(self.output_file)
        ]

        result = subprocess.run(cmd, capture_output=True, text=True, check=True)
        info = json.loads(result.stdout)

        duration = float(info["format"]["duration"])
        size_mb = int(info["format"]["size"]) / (1024 * 1024)

        video_stream = next(s for s in info["streams"] if s["codec_type"] == "video")
        audio_stream = next(s for s in info["streams"] if s["codec_type"] == "audio")

        return {
            "file": str(self.output_file),
            "duration_sec": round(duration, 2),
            "size_mb": round(size_mb, 2),
            "resolution": f"{video_stream['width']}x{video_stream['height']}",
            "video_codec": video_stream["codec_name"],
            "audio_codec": audio_stream["codec_name"],
            "audio_bitrate": audio_stream.get("bit_rate", "N/A")
        }

    def cleanup(self) -> None:
        """一時ファイルをクリーンアップ"""
        import shutil
        if self.temp_dir.exists():
            shutil.rmtree(self.temp_dir)
            print(f"🧹 一時ファイルを削除: {self.temp_dir}")

    def generate(self) -> dict:
        """動画生成の全工程を実行"""
        print("============================================================")
        print("🎬 Miyabi開発進捗 → 動画生成")
        print("============================================================")

        # Step 1: 音声ファイル収集
        audio_files = self.collect_audio_files()

        # Step 2: 音声ファイル連結
        merged_audio = self.concatenate_audio(audio_files)

        # Step 3: 動画生成
        self.generate_video(merged_audio)

        # Step 4: 動画情報取得
        info = self.get_video_info()

        # Step 5: クリーンアップ
        self.cleanup()

        print("\n============================================================")
        print("✅ 完了！動画ファイルを生成しました")
        print("============================================================")
        print(f"📁 出力ファイル: {info['file']}")
        print(f"⏱️  再生時間: {info['duration_sec']}秒")
        print(f"💾 ファイルサイズ: {info['size_mb']}MB")
        print(f"📺 解像度: {info['resolution']}")
        print(f"🎞️  Video Codec: {info['video_codec']}")
        print(f"🎤 Audio Codec: {info['audio_codec']}")
        print("\n📝 次のステップ:")
        print("  1. 動画を確認: open", info['file'])
        print("  2. YouTubeにアップロード")
        print()

        return info


def main():
    parser = argparse.ArgumentParser(
        description="VOICEVOX音声ファイルから動画を生成"
    )
    parser.add_argument(
        "-a", "--audio-dir",
        type=Path,
        default=Path("./output/audio"),
        help="音声ファイルのディレクトリ（デフォルト: ./output/audio）"
    )
    parser.add_argument(
        "-o", "--output",
        type=Path,
        default=Path("./output/miyabi-progress.mp4"),
        help="出力動画ファイルパス（デフォルト: ./output/miyabi-progress.mp4）"
    )
    parser.add_argument(
        "-t", "--thumbnail",
        type=Path,
        help="サムネイル画像パス（オプション、指定なしでデフォルト背景生成）"
    )

    args = parser.parse_args()

    # 音声ディレクトリの存在確認
    if not args.audio_dir.exists():
        print(f"❌ エラー: 音声ディレクトリが存在しません: {args.audio_dir}", file=sys.stderr)
        sys.exit(1)

    # 出力ディレクトリ作成
    args.output.parent.mkdir(parents=True, exist_ok=True)

    try:
        generator = VideoGenerator(args.audio_dir, args.output, args.thumbnail)
        info = generator.generate()

        # JSON形式で情報を出力（CI/CD統合用）
        print(json.dumps(info, indent=2, ensure_ascii=False))

    except Exception as e:
        print(f"❌ エラー: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
