#!/bin/bash
# Miyabi Headless Mode: Issue 自動処理
# Usage: ./01-process-issue.sh <issue_number>

set -e

ISSUE_NUM="${1:-}"
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
LOG_DIR="/tmp/miyabi-headless"
mkdir -p "$LOG_DIR"

# カラー出力
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

# 引数チェック
if [ -z "$ISSUE_NUM" ]; then
    log_error "Issue番号を指定してください"
    echo "Usage: $0 <issue_number>"
    exit 1
fi

log_info "=========================================="
log_info "Miyabi Headless Agent - Issue Processor"
log_info "=========================================="
log_info "Issue番号: #$ISSUE_NUM"
log_info "モード: Headless (自動実行)"
log_info "時刻: $(date '+%Y-%m-%d %H:%M:%S')"
log_info ""

# GitHub Issue 取得
log_info "Issue 情報を取得中..."
if ! gh issue view "$ISSUE_NUM" --json title,body,labels > "$LOG_DIR/issue-$ISSUE_NUM.json" 2>/dev/null; then
    log_error "Issue #$ISSUE_NUM が見つかりません"
    exit 1
fi

ISSUE_TITLE=$(jq -r '.title' "$LOG_DIR/issue-$ISSUE_NUM.json")
ISSUE_BODY=$(jq -r '.body' "$LOG_DIR/issue-$ISSUE_NUM.json")

log_success "Issue取得完了: $ISSUE_TITLE"
log_info ""

# Claude Code Headless Mode で処理
log_info "Claude Code Headless Mode で分析中..."

PROMPT="Analyze and process GitHub Issue #${ISSUE_NUM}:

Title: ${ISSUE_TITLE}

Description:
${ISSUE_BODY}

Instructions:
1. Analyze the issue and determine the required changes
2. List the files that need to be modified
3. Provide a step-by-step implementation plan
4. Estimate the complexity (Low/Medium/High)

Please respond with:
- Summary of the issue
- Required changes
- Implementation plan
- Complexity estimation
"

# Headless Mode 実行
if ! claude -p "$PROMPT" \
    --output-format json \
    --allowedTools "Read,Grep,Bash(git log),Bash(cargo tree)" \
    > "$LOG_DIR/analysis-$ISSUE_NUM.json" 2>&1; then
    log_error "Claude Code Headless 実行に失敗しました"
    cat "$LOG_DIR/analysis-$ISSUE_NUM.json"
    exit 1
fi

log_success "分析完了"
log_info ""

# 結果を解析
RESULT=$(jq -r '.result' "$LOG_DIR/analysis-$ISSUE_NUM.json" 2>/dev/null || echo "")
COST=$(jq -r '.total_cost_usd' "$LOG_DIR/analysis-$ISSUE_NUM.json" 2>/dev/null || echo "0")
DURATION=$(jq -r '.duration_ms' "$LOG_DIR/analysis-$ISSUE_NUM.json" 2>/dev/null || echo "0")

if [ -z "$RESULT" ]; then
    log_error "結果の取得に失敗しました"
    cat "$LOG_DIR/analysis-$ISSUE_NUM.json"
    exit 1
fi

log_info "=========================================="
log_info "分析結果"
log_info "=========================================="
echo "$RESULT"
log_info ""
log_info "実行時間: ${DURATION}ms"
log_info "コスト: \$${COST}"
log_info ""

# レポート生成
REPORT_FILE="$LOG_DIR/report-$ISSUE_NUM.md"
cat > "$REPORT_FILE" << EOF
# Issue #${ISSUE_NUM} 分析レポート

**Issue**: ${ISSUE_TITLE}
**分析日時**: $(date '+%Y-%m-%d %H:%M:%S')
**実行モード**: Headless (自動)
**実行時間**: ${DURATION}ms
**コスト**: \$${COST}

---

## 分析結果

${RESULT}

---

## メタデータ

- Issue番号: #${ISSUE_NUM}
- 分析ログ: \`$LOG_DIR/analysis-$ISSUE_NUM.json\`
- Issue情報: \`$LOG_DIR/issue-$ISSUE_NUM.json\`

🤖 Generated by Miyabi Headless Agent
EOF

log_success "レポート生成完了: $REPORT_FILE"

# Interactive Mode に通知（オプション）
if command -v osascript &> /dev/null; then
    osascript -e "display notification \"Issue #${ISSUE_NUM} の分析が完了しました\" with title \"Miyabi Headless Agent\" sound name \"Glass\""
fi

# VOICEVOX 通知（オプション）
if [ -f "$PROJECT_ROOT/tools/voicevox_enqueue.sh" ]; then
    "$PROJECT_ROOT/tools/voicevox_enqueue.sh" "Issue ${ISSUE_NUM} の分析が完了しました"
fi

log_success "=========================================="
log_success "処理完了"
log_success "=========================================="
log_info "レポート: $REPORT_FILE"

exit 0
